<!-- Head Section -->
<section class="page-section" data-background="<?php echo $this->basePath('images/4.jpg') ?>"
         style="padding: 215px 0 140px 0;">
    <div class="relative container align-left">

        <div class="row">

            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0" style="color: white"><?php echo $this->translate('Kontakt') ?></h1>

                                    <div class="hs-line-4 font-alt">
                                        <?php echo $this->translate('Masz do nas pytania? Zadzwoń lub napisz') ?>
                                    </div>
            </div>

            <div class="col-md-4 mt-30">
                <div class="mod-breadcrumbs font-alt align-right" style="color: white">
                    <a href="<?php echo $this->url('home', array('lang' => $lang)) ?>" style="color: white"><?php echo $this->translate('Home'); ?></a>&nbsp;/&nbsp;<a href="#" style="color: white"> <?php echo $this->translate('Kontakt') ?></a>
                </div>

            </div>
        </div>

    </div>
</section>
<!-- End Head Section -->

<!-- Contact Section -->
<section class="page-section" id="contact">
    <div class="container relative">

        <h2 class="font-alt mb-70 mb-sm-40 text-center">
            <?php echo $this->translate('Kontakt'); ?>
        </h2>

        <p class="text-center" style="font-size: 22px; text-transform: uppercase; letter-spacing: 3px;">
            <span style="font-weight: bold">Tartak bogdan Michalski</span> | racot, ul. szkolna 23 | 64-000 Kościan <br/>
            tel.: 65 513 14 54 | fax.: 65 513 10 11 | <span style="text-transform: lowercase">biuro@tartakmichalski.pl</span>
        </p>

        <p class="text-center" style="font-size: 16px; text-transform: uppercase;">
            Konto bankowe: <br/>
            Bank Spółdzielczy w Kościanie <br/>
            44-8666-0004-0101-0894-2000-0002 <br/>
        </p>

        <div class="row" style="margin-bottom: 40px">

            <!-- Team item -->
            <div class="col-sm-4 mb-xs-30 wow fadeInUp">
                <div>

                    <div class="team-item-image">

                        <img src="<?php echo $this->basePath('/images/arleta.jpg') ?>" alt="" />

                    </div>

                    <div class="team-item-descr font-alt">

                        <div class="team-item-name">
                            Sekretariat
                        </div>

                        <div class="team-item-role">
                            Arleta Szcześniak – Laskowska <br>
                            tel. 655131454, 655131012, fax. 655131011
                        </div>

                    </div>

                </div>
            </div>
            <!-- End Team item -->

            <!-- Team item -->
            <div class="col-sm-4 mb-xs-30 wow fadeInUp" data-wow-delay="0.1s">
                <div>

                    <div class="team-item-image">

                        <img src="<?php echo $this->basePath('/images/daria.jpg') ?>" alt="" />

                    </div>

                    <div class="team-item-descr font-alt">

                        <div class="team-item-name">
                            BIURO OBSŁUGI KLIENTA
                        </div>

                        <div class="team-item-role">
                            Daria Roszak <br>
                            kom. 503 074 222
                        </div>

                    </div>

                </div>
            </div>
            <!-- End Team item -->

            <!-- Team item -->
            <div class="col-sm-4 mb-xs-30 wow fadeInUp" data-wow-delay="0.2s">
                <div>

                    <div class="team-item-image">

                        <img src="<?php echo $this->basePath('/images/anna.jpg') ?>" alt="" />

                    </div>

                    <div class="team-item-descr font-alt">

                        <div class="team-item-name">
                            BIURO OBSŁUGI KLIENTA
                        </div>

                        <div class="team-item-role">
                            Anna Majcherek <br>
                            kom. 503 074 222
                        </div>

                    </div>

                </div>
            </div>
            <!-- End Team item -->

        </div>

        <div class="row" style="margin-bottom: 40px">

            <!-- Team item -->
            <div class="col-sm-4 col-sm-offset-2 mb-xs-30 wow fadeInUp">
                <div>

                    <div class="team-item-image">

                        <img src="<?php echo $this->basePath('/images/magda.jpg') ?>" alt="" />

                    </div>

                    <div class="team-item-descr font-alt">

                        <div class="team-item-name">
                            BIURO OBSŁUGI KLIENTA
                        </div>

                        <div class="team-item-role">
                            Magdalena Michalska – Ratajczak <br>
                            tel. 65 513 14 54
                        </div>

                    </div>

                </div>
            </div>
            <!-- End Team item -->

            <!-- Team item -->
<!--            <div class="col-sm-4 mb-xs-30 wow fadeInUp" data-wow-delay="0.1s">-->
<!--                <div>-->
<!---->
<!--                    <div class="team-item-image">-->
<!---->
<!--                        <img src="--><?php //echo $this->basePath('/images/karol.jpg') ?><!--" alt="" />-->
<!---->
<!--                    </div>-->
<!---->
<!--                    <div class="team-item-descr font-alt">-->
<!---->
<!--                        <div class="team-item-name">-->
<!--                            TARCICA SUCHA-->
<!--                        </div>-->
<!---->
<!--                        <div class="team-item-role">-->
<!--                            Karol Barcz <br>-->
<!--                            kom. 515 659 333-->
<!--                        </div>-->
<!---->
<!--                    </div>-->
<!---->
<!--                </div>-->
<!--            </div>-->
            <!-- End Team item -->

            <!-- Team item -->
            <div class="col-sm-4 mb-xs-30 wow fadeInUp" data-wow-delay="0.2s">
                <div>

                    <div class="team-item-image">

                        <img src="<?php echo $this->basePath('/images/maciej.jpg') ?>" alt="" />

                    </div>

                    <div class="team-item-descr font-alt">

                        <div class="team-item-name">
                            DESKI PODŁOGOWE <br>
                            I TARASOWE, DRZWI, SCHODY
                        </div>

                        <div class="team-item-role">
                            Maciej Nowak <br>
                            kom. 502 074 950
                        </div>

                    </div>

                </div>
            </div>
            <!-- End Team item -->

        </div>

        <!-- Contact Form -->
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                <form class="form contact-form" id="contact_form">
                    <div class="clearfix">

                        <div class="cf-left-col">

                            <!-- Name -->
                            <div class="form-group">
                                <input type="text" name="name" id="name" class="input-md round form-control" placeholder="<?php echo $this->translate('Imię'); ?>" pattern=".{3,100}" required>
                            </div>

                            <!-- Email -->
                            <div class="form-group">
                                <input type="text" name="surname" id="surname" class="input-md round form-control" placeholder="<?php echo $this->translate('Nazwisko'); ?>" pattern=".{5,100}" required>
                            </div>

                        </div>

                        <div class="cf-right-col">

                            <!-- Message -->
                            <div class="form-group">
                                <textarea name="message" id="message" class="input-md round form-control" style="height: 84px;" placeholder="<?php echo $this->translate('Wiadomość'); ?>"></textarea>
                            </div>

                        </div>

                    </div>

                    <div class="clearfix">

                        <div class="cf-left-col">

                            <!-- Name -->
                            <div class="form-group">
                                <input type="text" name="phone" id="phone" class="input-md round form-control" placeholder="<?php echo $this->translate('Telefon'); ?>" pattern=".{3,100}" required>
                            </div>

                        </div>

                        <div class="cf-right-col">

                            <!-- Send Button -->
                            <div class="align-right pt-10">
                                <button class="submit_btn btn btn-mod btn-medium btn-round" id="submit_btn"><?php echo $this->translate('Wyślij wiadomość'); ?></button>
                            </div>

                        </div>

                    </div>



                    <div id="result"></div>
                </form>

            </div>
        </div>
        <!-- End Contact Form -->

    </div>
</section>
<!-- End Contact Section -->