<!-- Head Section -->
<section class="page-section" data-background="<?php echo $this->basePath('images/4.jpg') ?>"
         style="padding: 215px 0 140px 0;">
    <div class="relative container align-left">

        <div class="row">

            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0" style="color: white"><?php echo $this->translate('Kontakt') ?></h1>

                                    <div class="hs-line-4 font-alt">
                                        <?php echo $this->translate('Masz do nas pytania? Zadzwoń lub napisz') ?>
                                    </div>
            </div>

            <div class="col-md-4 mt-30">
                <div class="mod-breadcrumbs font-alt align-right" style="color: white">
                    <a href="<?php echo $this->url('home', array('lang' => $lang)) ?>" style="color: white"><?php echo $this->translate('Home'); ?></a>&nbsp;/&nbsp;<a href="#" style="color: white"> <?php echo $this->translate('Kontakt') ?></a>
                </div>

            </div>
        </div>

    </div>
</section>
<!-- End Head Section -->