<?php /* @var $history \CmsIr\Page\Model\Page */ ?>
<?php if(isset($history)): ?>
    <section class="page-section" id="historia">
        <div class="container relative">

            <h2 class="font-alt mb-sm-40 text-center">
                <?php echo $history->getTitle() ?>
            </h2>

            <div class="section-text">

                <div class="row">

                    <!-- Team item -->
                    <div class="col-md-4 mb-xs-30 wow fadeInUp">
                        <div class="team-item">

                            <?php $files = reset($history->getFiles()) ?>

                            <?php if(isset($files)): ?>

                                <img src="<?php echo $this->basePath('files/page/' . $files->getFilename()) ?>" alt="historia"/>

                            <?php endif ?>

                            <div class="team-item-descr font-alt">

                                <div class="team-item-name">
                                    TARTAK MICHALSKI
                                </div>

                                <div class="team-item-role">
                                    ROK 1972
                                </div>

                            </div>

                        </div>
                    </div>
                    <!-- End Team item -->

                    <?php $content = $history->getContent() ?>
                    <?php if(isset($content)): ?>
                        <?php $output = str_split($content, 760) ?>
                        <?php if(isset($output[1])): ?>

                            <?php $dot = strripos($content, '.') ?>
                            <?php $output[0] = substr($output[0], 0, 760 - $dot) ?>
                            <?php $output[1] = substr($output[1], 760 - $dot) ?>

                        <?php endif ?>

                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">

                            <?php echo $output[0] ?>

                        </div>

                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">

                            <?php echo isset($output[1]) ? $output[1] : '' ?>

                        </div>

                    <?php endif ?>

                </div>

            </div>

            <div class="align-right" style="margin-right: 50px; margin-top: -40px">
                <a href="<?php echo $this->url('view-page', array('lang' => $lang, 'url' => $history->getUrl())) ?>" class="section-more font-alt"><i class="fa fa-angle-down fa-2x"></i>
                <?php echo $this->translate('Czytaj więcej'); ?></a>
            </div>

        </div>
    </section>
    <!-- End Services Section -->

<?php endif ?>

<!-- Call Action Section -->
<section class="small-section bg-dark">
    <div class="container relative">

        <div class="align-center">
            <img src="images/logo_tartak_1.svg" alt="logo" class="img-responsive center-block" style="height: 100px"/>
        </div>

    </div>
</section>
<!-- End Call Action Section -->

<?php if(!empty($posts)): ?>

    <!-- About Section -->
    <section class="page-section" id="about">
        <div class="container relative">

            <h2 class="font-alt align-center mb-50 mb-sm-40">
                <?php echo $this->translate('Aktualności') ?>

                        <span class="section-title font-alt align-center mb-50 mb-sm-40"
                              style="position: absolute; right: 3%;">

                            <a href="<?php echo $this->url('news-list', array('lang' => $lang)) ?>" class="section-more right" style="letter-spacing: 0.2em !important;">
                                <?php echo $this->translate('Zobacz wszystkie aktualności'); ?> <i class="fa fa-angle-right"></i></a>

                        </span>

            </h2>

            <div class="row multi-columns-row">

                <?php /* @var $post \CmsIr\Post\Model\Post */ ?>
                <?php foreach($posts as $post): ?>
                    <?php $files = $post->getFiles() ?>

                    <!-- Post Item -->
                    <div class="col-sm-6 col-md-4 col-lg-4 mb-60 mb-xs-40">

                        <div class="post-prev-img">
                            <a href="<?php echo $this->url('view-news', array('lang' => $lang, 'url' => $post->getUrl())) ?>">

                                <?php if(empty($files)): ?>

                                    <img src="images/blog/post-prev-1.jpg" alt=""/>

                                <?php else: ?>

                                    <?php /* @var $file \CmsIr\File\Model\File */ ?>
                                    <?php $file = reset($files) ?>

                                    <img src="<?php echo $this->basePath('files/post/' . $file->getFilename()) ?>" alt=""/>

                                <?php endif ?>

                            </a>
                        </div>

                        <div class="post-prev-title font-alt">
                            <a href="<?php echo $this->url('view-news', array('lang' => $lang, 'url' => $post->getUrl())) ?>"><?php echo $post->getTitle() ?></a>
                        </div>

                        <div class="post-prev-info font-alt">
                            <?php echo $post->getAuthor() ?> | <?php echo $post->getDate() ?>
                        </div>

                        <div class="post-prev-text">
                            <?php echo mb_substr($post->getContent(), 0 , 200, 'utf-8') ?>
                        </div>

                        <div class="post-prev-more">
                            <a href="<?php echo $this->url('view-news', array('lang' => $lang, 'url' => $post->getUrl())) ?>" class="btn btn-mod btn-gray btn-round"><?php echo $this->translate('Zobacz więcej'); ?> <i
                                    class="fa fa-angle-right"></i></a>
                        </div>

                    </div>
                    <!-- End Post Item -->

                <?php endforeach ?>

            </div>

        </div>
    </section>
    <!-- End About Section -->

<?php endif ?>

<!-- Divider -->
<hr class="mt-0 mb-0 "/>
<!-- End Divider -->

<?php if(!empty($categories)): ?>

    <!-- Services Section -->
    <section class="page-section" id="services">
        <div class="container relative">

            <h2 class="font-alt mb-sm-40 text-center">
                <?php echo $this->translate('Oferta'); ?>
            </h2>

            <!-- Nav tabs -->
            <ul class="nav nav-tabs tpl-alt-tabs font-alt pt-30 pt-sm-0 pb-30 pb-sm-0">

                <?php /* @var $category \CmsIr\Category\Model\Category */ ?>
                <?php foreach($categories as $k => $category): ?>

                    <?php
                        switch ($category->getName())
                        {
                            case 'TARCICA SUCHA':
                                $img = '<img src="images/tarcica.png" alt="tarcica"/>';
                                break;
                            case 'DESKA PODŁOGOWA':
                                $img = '<img src="images/deska.png" alt="tarcica"/>';
                                break;
                            case 'WIĘŹBA DACHOWA SOSNA':
                                $img = '<img src="images/wiezba.png" alt="tarcica"/>';
                                break;
                            case 'ELEMENTY KLEJONE':
                                $img = '<img src="images/klejone.png" alt="tarcica"/>';
                                break;
                            case 'RAMIAK DRZWIOWY':
                                $img = '<img src="images/ramiak.png" alt="tarcica"/>';
                                break;
                            case 'AKCESORIA PODŁOGOWE':
                                $img = '<img src="images/akcesoria.png" alt="tarcica"/>';
                                break;
                            default:
                                $img = '<img src="images/tarcica.png" alt="tarcica"/>';
                        }
                    ?>

                    <li <?php echo $k == 0 ? 'class="active"' : '' ?>>
                        <a href="#<?php echo $category->getId() ?>" data-toggle="tab">

                            <div class="alt-tabs-icon">
                                <?php echo $img ?>
                            </div>

                            <?php echo $category->getTitle() ?>
                        </a>
                    </li>

                <?php endforeach ?>

            </ul>
            <!-- End Nav tabs -->

            <!-- Tab panes -->
            <div class="tab-content tpl-tabs-cont">

            <?php foreach($categories as $k => $category): ?>

                <div class="tab-pane fade in <?php echo $k == 0 ? 'active' : '' ?>" id="<?php echo $category->getId() ?>">

                    <div class="section-text">
                        <div class="row">
                            <div class="col-md-4 mb-md-40 mb-xs-30">

                                <?php if(!empty($category->getFilename())): ?>

                                    <img src="<?php echo $this->basePath('files/category/' . $category->getFilename()) ?>" alt="deski"/>

                                <?php endif ?>
                            </div>
                            <div class="col-md-8 col-sm-6 mb-sm-50 mb-xs-30">

                               <?php echo $category->getContent() ?>

                            </div>
                        </div>
                    </div>

                    <div class="align-right" style="margin-right: 50px; margin-top: -40px">
                        <a href="<?php echo $this->url('offer-list', array('lang' => $lang)) ?>" class="section-more font-alt"><i class="fa fa-angle-down fa-2x"></i> Zobacz asortyment</a>
                    </div>

                </div>

            <?php endforeach ?>

            </div>

        </div>
    </section>
    <!-- End Services Section -->

<?php endif ?>

<?php if(!empty($opinions)): ?>

    <section class="page-section bg-gray fullwidth-slider1 bg-scroll" data-background="images/slider-tlo.png" style="padding: 125px 0">

        <?php /* @var $opinion \CmsIr\Post\Model\Post */ ?>
        <?php foreach($opinions as $opinion): ?>

            <!-- Slide Item -->
            <div>
                <div class="container relative">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 align-center">

                            <!-- Section Title -->
                            <h2 class="small-title font-alt" style="color: white; opacity: .8;"><?php echo $this->translate('Opinie klientów na nasz temat'); ?></h2>
                            <blockquote class="testimonial" style="color: white">

                                <?php echo $opinion->getContent() ?>

                                <footer class="testimonial-author">

                                    <?php echo $opinion->getClient() ?>

                                </footer>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Slide Item -->

        <?php endforeach ?>

    </section>
    <!-- End Testimonials Section -->

<?php endif ?>

<!-- Shop Section -->
<section class="page-section">
    <div class="container relative">

        <h2 class="font-alt align-center mb-70 mb-sm-40">
            Bestsellery w ofercie

            <span class="section-title font-alt align-center mb-70 mb-sm-40"
                  style="position: absolute; right: 3%;">

                <a href="#" class="section-more right" style="letter-spacing: 0.2em !important;">Zobacz
                    wszystkie <i class="fa fa-angle-right"></i></a>

            </span>

        </h2>

        <div class="row multi-columns-row">

            <!-- Shop Item -->
            <div class="col-md-3 col-lg-3 mb-60 mb-xs-40 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                <div class="post-prev-img">
                    <a href="shop-single.html"><img src="images/shop/shop-prev-1.jpg" alt=""/></a>
                </div>
                <div class="post-prev-title font-alt align-center">
                    <a href="shop-single.html">G-Star Polo Applique Jersey</a>
                </div>
                <div class="post-prev-more align-center">
                    <a href="#" class="btn btn-mod btn-gray btn-round">Zobacz więcej <i class="fa fa-angle-right"></i></a>
                </div>
            </div>
            <!-- End Shop Item -->

            <!-- Shop Item -->
            <div class="col-md-3 col-lg-3 mb-60 mb-xs-40 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                <div class="post-prev-img">
                    <a href="shop-single.html"><img src="images/shop/shop-prev-1.jpg" alt=""/></a>
                </div>
                <div class="post-prev-title font-alt align-center">
                    <a href="shop-single.html">G-Star Polo Applique Jersey</a>
                </div>
                <div class="post-prev-more align-center">
                    <a href="#" class="btn btn-mod btn-gray btn-round">Zobacz więcej <i class="fa fa-angle-right"></i></a>
                </div>
            </div>
            <!-- End Shop Item --> <!-- Shop Item -->
            <div class="col-md-3 col-lg-3 mb-60 mb-xs-40 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                <div class="post-prev-img">
                    <a href="shop-single.html"><img src="images/shop/shop-prev-1.jpg" alt=""/></a>
                </div>
                <div class="post-prev-title font-alt align-center">
                    <a href="shop-single.html">G-Star Polo Applique Jersey</a>
                </div>
                <div class="post-prev-more align-center">
                    <a href="#" class="btn btn-mod btn-gray btn-round">Zobacz więcej <i class="fa fa-angle-right"></i></a>
                </div>
            </div>
            <!-- End Shop Item --> <!-- Shop Item -->
            <div class="col-md-3 col-lg-3 mb-60 mb-xs-40 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                <div class="post-prev-img">
                    <a href="shop-single.html"><img src="images/shop/shop-prev-1.jpg" alt=""/></a>
                </div>
                <div class="post-prev-title font-alt align-center">
                    <a href="shop-single.html">G-Star Polo Applique Jersey</a>
                </div>
                <div class="post-prev-more align-center">
                    <a href="#" class="btn btn-mod btn-gray btn-round">Zobacz więcej <i class="fa fa-angle-right"></i></a>
                </div>
            </div>
            <!-- End Shop Item -->

        </div>

    </div>
</section>
<!-- End Shop Section -->
