<!-- Services Section -->
<section class="page-section" id="services">
    <div class="container relative">

        <h2 class="section-title font-alt mb-70 mb-sm-40">
            Usługi
        </h2>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs tpl-alt-tabs font-alt pt-30 pt-sm-0 pb-30 pb-sm-0">
            <li class="active">
                <a href="#service-web-design" data-toggle="tab">

                    <div class="alt-tabs-icon">
                        <span class="icon-desktop"></span>
                    </div>

                    Web Design
                </a>
            </li>
            <li>
                <a href="#service-graphic" data-toggle="tab">

                    <div class="alt-tabs-icon">
                        <span class="icon-tools"></span>
                    </div>

                    Graphic Design
                </a>
            </li>
            <li>
                <a href="#service-development" data-toggle="tab">

                    <div class="alt-tabs-icon">
                        <span class="icon-gears"></span>
                    </div>

                    Development
                </a>
            </li>
            <li>
                <a href="#service-photography" data-toggle="tab">

                    <div class="alt-tabs-icon">
                        <span class="icon-camera"></span>
                    </div>

                    Photography
                </a>
            </li>
        </ul>
        <!-- End Nav tabs -->

        <!-- Tab panes -->
        <div class="tab-content tpl-tabs-cont">

            <!-- Service Item -->
            <div class="tab-pane fade in active" id="service-web-design">

                <div class="section-text">
                    <div class="row">
                        <div class="col-md-4 mb-md-40 mb-xs-30">
                            <blockquote class="mb-0">
                                <p>
                                    It&nbsp;doesn&rsquo;t matter how many times&nbsp;I have to&nbsp;click, as&nbsp;long
                                    as&nbsp;each click is&nbsp;a&nbsp;mindless, unambiguous choice.
                                </p>
                                <footer>
                                    Steve Krug
                                </footer>
                            </blockquote>
                        </div>
                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
                            Cras mi tortor, laoreet id ornare et, accumsan non magna. Maecenas vulputate accumsan velit.
                            Curabitur a nulla ex. Nam a tincidunt ante. Vitae gravida turpis. Vestibulum varius
                            nulla non nulla scelerisque tristique.
                        </div>
                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
                            Mauris id viverra augue, eu porttitor diam. Praesent faucibus est a interdum elementum.
                            Nam varius at ipsum id dignissim. Nam a tincidunt ante lorem. Pellentesque suscipit ante
                            at ullamcorper pulvinar neque porttitor.
                        </div>
                    </div>
                </div>

            </div>
            <!-- End Service Item -->

            <!-- Service Item -->
            <div class="tab-pane fade" id="service-graphic">

                <div class="section-text">
                    <div class="row">
                        <div class="col-md-4 mb-md-40 mb-xs-30">
                            <blockquote class="mb-0">
                                <p>
                                    Never fall in&nbsp;love with an&nbsp;idea. They&rsquo;re whores. If&nbsp;the one you&rsquo;re with isn&rsquo;t doing the job, there&rsquo;s always another.
                                </p>
                                <footer>
                                    Chip Kidd
                                </footer>
                            </blockquote>
                        </div>
                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
                            Lorem ipsum dolor sit semper amet, consectetur adipiscing elit. In maximus ligula metus pellentesque
                            mattis. Donec vel ultricies purus. Nam dictum sem, ipsum aliquam . Praesent sed nisi eleifend,
                            fermentum orci amet, iaculis libero.
                        </div>
                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">

                            Pellentesque suscipit ante at ullamcorper pulvinar neque porttitor. Integer lectus. Etiam sit amet
                            fringilla lacus. Maecenas  volutpat, diam enim sagittis quam, id porta quam. Sed id&nbsp;dolor
                            consectetur fermentum volutpat nibh, accumsan purus.
                        </div>
                    </div>
                </div>

            </div>
            <!-- End Service Item -->

            <!-- Service Item -->
            <div class="tab-pane fade" id="service-development">

                <div class="section-text">
                    <div class="row">
                        <div class="col-md-4 mb-md-40 mb-xs-30">
                            <blockquote class="mb-0">
                                <p>
                                    All that is&nbsp;valuable in&nbsp;human society depends upon the opportunity for development accorded the individual.
                                </p>
                                <footer>
                                    Albert Einstein
                                </footer>
                            </blockquote>
                        </div>
                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
                            Fusce hendrerit vitae nunc id gravida. Donec euismod quis ante at mattis. Mauris dictum ante sit
                            amet enim interdum semper. Vestibulum odio justo, faucibus et dictum eu, malesuada nec neque.
                            Maecenas  volutpat, diam enim sagittis.
                        </div>
                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
                            Pellentesque suscipit ante at ullamcorper pulvinar neque porttitor. Sed id dolor consectetur fermentum
                            volutpat nibh, accumsan purus. Lorem ipsum dolor sit semper amet, consectetur adipiscing elit.
                            Inmed maximus ligula metus pellentesque.
                        </div>
                    </div>
                </div>

            </div>
            <!-- End Service Item -->

            <!-- Service Item -->
            <div class="tab-pane fade" id="service-photography">

                <div class="section-text">
                    <div class="row">
                        <div class="col-md-4 mb-md-40 mb-xs-30">
                            <blockquote class="mb-0">
                                <p>
                                    Photography is&nbsp;the simplest thing in&nbsp;the world, but it&nbsp;is&nbsp;incredibly
                                    complicated to&nbsp;make it&nbsp;really work.
                                </p>
                                <footer>
                                    Martin Parr
                                </footer>
                            </blockquote>
                        </div>
                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
                            Donec vel ultricies purus. Nam dictum sem, ipsum aliquam . Etiam sit amet fringilla lacus.
                            Pellentesque suscipit ante at ullamcorper pulvinar neque porttitor. Integer lectus.
                            Praesent sed nisi eleifend, fermentum orci amet, iaculis libero.
                        </div>
                        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
                            Maecenas  volutpat, diam enim sagittis quam, id porta quam. Sed id dolor consectetur fermentum
                            volutpat nibh, accumsan purus. Lorem ipsum dolor sit semper amet, consectetur adipiscing elit.
                            In maximus ligula metus pellentesque mattis.
                        </div>
                    </div>
                </div>

            </div>
            <!-- End Service Item -->

        </div>
        <!-- End Tab panes -->


    </div>
</section>
<!-- End Services Section -->

<!-- Call Action Section -->
<section class="small-section bg-dark">
    <div class="container relative">

        <div class="align-center">
<!--            <h3 class="banner-heading font-alt">Want to discuss your new project?</h3>-->
<!--            <div>-->
<!--                <a href="" class="btn btn-mod btn-w btn-medium btn-round">Lets tallk</a>-->
<!--            </div>-->
        </div>

    </div>
</section>
<!-- End Call Action Section -->

<!-- Blog Section -->
<section class="page-section" id="news">
    <div class="container relative">

        <h2 class="section-title font-alt align-left mb-70 mb-sm-40">
           Ostatnie newsy

            <a href="<?php echo $this->url('news-list' ,array('lang' => $lang)) ?>" class="section-more right">Zobacz wszystkie <i class="fa fa-angle-right"></i></a>

        </h2>

        <div class="row multi-columns-row">

            <?php if(!empty($posts)): ?>

                <?php /* @var $post \CmsIr\Post\Model\Post */ ?>
                <?php foreach($posts as $post): ?>
                    <?php $postFile = $post->getFilenameMain() ?>

                    <!-- Post Item -->
                    <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">

                        <div class="post-prev-img">
                            <a href="<?php echo $this->url('view-news', array('lang' => $lang, 'url' => $post->getUrl())) ?>">

                                <?php if(empty($postFile)): ?>

                                    <img src="images-front/blog/post-prev-1.jpg" alt=""/>

                                <?php else: ?>

                                    <img src="<?php echo $this->url('thumb', array('entity' => 'post', 'size' => '360x202', 'filename' => $postFile))?>" alt="news"/>

                                <?php endif ?>

                            </a>
                        </div>

                        <div class="post-prev-title font-alt">
                            <a href="<?php echo $this->url('view-news', array('lang' => $lang, 'url' => $post->getUrl())) ?>"><?php echo $post->getTitle() ?></a>
                        </div>

                        <div class="post-prev-info font-alt">

                            <?php $date = $post->getDate() ?>
                            <?php $date = explode(' ', $date) ?>
                            <?php echo $post->getAuthor() ?> | <?php echo $date[0] . ' ' . $this->translate($date['1']) ?>

                        </div>

                        <div class="post-prev-text">
                            <?php echo mb_substr($post->getContent(), 0 , 200, 'utf-8') ?>
                        </div>

                        <div class="post-prev-more">
                            <a href="<?php echo $this->url('view-news', array('lang' => $lang, 'url' => $post->getUrl())) ?>" class="btn btn-mod btn-gray btn-round">Zobacz więcej <i class="fa fa-angle-right"></i></a>
                        </div>

                    </div>
                    <!-- End Post Item -->

                <?php endforeach ?>

            <?php endif ?>

        </div>

    </div>
</section>
<!-- End Blog Section -->