<?php /* @var $page \CmsIr\Page\Model\Page */ ?>

<!-- * * * * * * * * * * * * * * * * * *
                    PAGE TITLE
    * * * * * * * * * * * * * * * * * * * -->
<?php $background = $page->getFilenameBackground() ?>

<section class="az-page-title-section" <?php echo !empty($background) ? 'style="background-image : url(' . $this->basepath("files/page/" . $background) . '); background-repeat: no-repeat;
    background-size: 100% 100%; "' : '' ?>>
    <div class="container">
	<div class="row">
	    <h1><?php echo $page->getTitle() ?></h1>

	    <!--<h3>Z ŻYCIA ZESPOŁU</h3>-->
	</div>
    </div>
    <div class="az-breadcumb">
	<a href="<?php echo $this->url('home') ?>">HOME</a>
	<span><?php echo $page->getTitle() ?></span>
    </div>
</section>
    <!-- PAGE TITLE END -->

<!-- * * * * * * * * * * * * * * * * * *
		BLOG SINGLE
* * * * * * * * * * * * * * * * * * * -->
<section class="az-blog-single-section az-section">
    <div class="container">
	<div class="row">
	    <!-- SINGLE CONTENT -->
	    <div class="az-blog-single-content">
		<!-- POST TITLE -->
		<div class="az-blog-page-title-meta">
		    <h1><?php echo $page->getSubtitle() ?></h1>
		    <!--<span class="az-post-date">2015-08-20</span>-->

		    <!--<p class="az-post-meta">autor: <a href="#" class="az-post-author">Marta Cugier</a>, kategoria:-->
			<!--<a href="#" class="az-post-category">Koncerty</a></p>-->
		</div>
		<!-- POST TITLE END -->

		<div class="az-blog-single-details">
		    <!-- POST IMAGE -->

		    <?php if(!empty($page->getFilenameMain())): ?>

			<div class="az-blog-page-feat-img">
			    <img src="<?php echo $this->url('thumb', array('entity' => 'page', 'size' => '900x600', 'filename' => $page->getFilenameMain()))  ?>" alt="Blog Single Image">
			</div>

		    <?php endif ?>
		    <!-- POST IMAGE END -->

		    <!-- POST TEXT -->
		    <div class="az-blog-page-details-text">

			<?php echo $page->getContent() ?>

		    </div>
		</div>
		<!-- ABOUT US END -->
	    </div>
	</div>
    </div>
</section>

<?php if(!empty($page->getFiles())): ?>
    <?php $files = $page->getFiles() ?>
    <?php $chunk = array_chunk($files, 3) ?>

    <section class="az-blog-single-section az-section">
	<div class="container">

	    <?php foreach ($chunk as $c): ?>

		<div class="row" style="margin-bottom: 20px">

		    <?php /* @var $file CmsIr\File\Model\File */ ?>
		    <?php foreach ($c as $file): ?>

			<div class="az-team-member col-md-4 col-sm-3 col-xs-12">
			    <div class="az-team-img-wrapper">
				<a href="<?php echo $this->basePath('files/page/' . $file->getFilename()) ?>" class="az-lightbox">
				    <img src="<?php echo $this->basePath('files/page/' . $file->getFilename()) ?>" alt="Płyta">
				</a>
			    </div>
			</div>

		    <?php endforeach ?>

		</div>

	    <?php endforeach ?>

	</div>
    </section>

<?php endif ?>