<?php /* @var $post \CmsIr\Post\Model\Post */ ?>
<?php $files = $post->getFiles() ?>

<?php if(!empty($post->getFilenameBackground())): ?>

    <!-- Head Section -->
    <section class="page-section"
             style="padding: 215px 0 140px 0; background: url(<?php echo $this->basePath('files/post/' . $post->getFilenameBackground()) ?>) no-repeat; background-size: 100% 100%;">
    <div class="relative container align-left">

            <div class="row">

                <div class="col-md-8">
                    <h1 class="hs-line-11 font-alt mb-20 mb-xs-0" style="color: white"><?php echo $post->getTitle() ?></h1>

    <!--                <div class="hs-line-4 font-alt">-->
    <!--                    Najnowsze ciekawostki i informacje z naszej branży-->
    <!--                </div>-->
                </div>

                <div class="col-md-4 mt-30">
                    <div class="mod-breadcrumbs font-alt align-right" style="color: white">
                        <a href="<?php echo $this->url('home', array('lang' => $lang)) ?>" style="color: white"><?php echo $this->translate('Home'); ?></a>&nbsp;/&nbsp;<a href="#" style="color: white"><?php echo $post->getTitle() ?></a>
                    </div>

                </div>
            </div>

        </div>
    </section>
    <!-- End Head Section -->

<?php endif ?>

<!-- Section -->
<section class="page-section">
    <div class="container relative">

        <div class="row">

            <!-- Content -->
            <div class="col-sm-10 col-sm-offset-1">

                <!-- Post -->
                <div class="blog-item">

                    <?php $date = explode(' ', $post->getDate()) ?>

                    <!-- Date -->
                    <div class="blog-item-date">
                        <span class="date-num"><?php echo $date[0] ?></span><?php echo $date[1] ?>
                    </div>

                    <!-- Post Title -->
                    <h2 class="blog-item-title font-alt"><?php echo $post->getTitle() ?></h2>

                    <!-- Author, Categories, Comments -->
                    <div class="blog-item-data">
                        <i class="fa fa-user"></i> <?php echo $post->getAuthor() ?>
                    </div>

                    <?php if(!empty($files)): ?>

                        <!-- Media Gallery -->
                        <div class="blog-media">
                            <ul class="clearlist content-slider">

                                <?php /* @var $file \CmsIr\File\Model\File */ ?>
                                <?php foreach($files as $file): ?>

                                    <li>
                                        <img class="img-responsive" style="max-height: 532px" src="<?php echo $this->basePath('files/post/' . $file->getFilename()) ?>" alt=""/>
                                    </li>

                                <?php endforeach ?>

                            </ul>
                        </div>

                    <?php endif ?>

                    <!-- Text Intro -->
                    <div class="blog-item-body">
                        <?php echo $post->getContent() ?>
                    </div>

                </div>
                <!-- End Post -->

            </div>
            <!-- End Content -->

        </div>

    </div>
</section>
<!-- End Section -->