<?php /* @var $person \Team\Model\Team*/ ?>

	<!-- * * * * * * * * * * * * * * * * * *
                      PAGE TITLE
      * * * * * * * * * * * * * * * * * * * -->
	<section class="az-page-title-section">
		<div class="container">
			<div class="row">
				<h1>Zespół</h1>

				<!--<h3>Z ŻYCIA ZESPOŁU</h3>-->
			</div>
		</div>
		<div class="az-breadcumb">
			<a href="<?php echo $this->url('home') ?>">HOME</a>
			<span><?php echo $person->getFirstName() ?></span>
		</div>
	</section>
	<!-- PAGE TITLE END -->

<!-- * * * * * * * * * * * * * * * * * *
		BLOG SINGLE
* * * * * * * * * * * * * * * * * * * -->
<section class="az-blog-single-section az-section">
    <div class="container">
	<div class="row">
	    <!-- SINGLE CONTENT -->
	    <div class="az-blog-single-content">
		<!-- POST TITLE -->
		<div class="az-blog-page-title-meta">
		    <h1><?php echo $person->getFirstName() ?></h1>
		    <!--<span class="az-post-date">2015-08-20</span>-->

		    <!--<p class="az-post-meta">autor: <a href="#" class="az-post-author">Marta Cugier</a>, kategoria:-->
			<!--<a href="#" class="az-post-category">Koncerty</a></p>-->
		</div>
		<!-- POST TITLE END -->

		<div class="az-blog-single-details">
		    <!-- POST IMAGE -->

		    <?php if(!empty($person->getFilenameMain())): ?>

			<div class="az-blog-page-feat-img">
			    <img src="<?php echo $this->url('thumb', array('entity' => 'team', 'size' => '900x600', 'filename' => $person->getFilenameMain()))  ?>" alt="Blog Single Image">
			</div>

		    <?php endif ?>
		    <!-- POST IMAGE END -->

		    <!-- POST TEXT -->
		    <div class="az-blog-page-details-text">

			<?php echo $person->getContent() ?>

		    </div>
		</div>
		<!-- ABOUT US END -->
	    </div>
	</div>
    </div>
</section>