<!-- Modal -->
<div class="modal fade" id="statusMassiveModal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Zmiana statusu</h4>
            </div>
            <form action="" method="post">
                <div class="modal-body">
                    <div class="content">
                        <div class="form-group  has-feedback">
                            <label for="status">Status</label>
                            <select class="form-control" name="status" id="status">
                                <option value="1">Aktywny</option>
                                <option value="2">Nieaktywny</option>
                            </select>
                        </div>
                    </div>
                    <div class="message">
                        <p>
                            Zaznacz elementy na liście.
                        </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <img src="/img/ajax-loader.gif" alt="spinner" class="pull-left spinner" />
                    <input type="submit" name="del" value="Anuluj" class="btn btn-default" data-dismiss="modal"/>
                    <input type="submit" name="del" value="Zapisz" class="btn btn-primary" />
                </div><!-- /.modal-footer -->

            </form>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-doalog -->
</div><!-- /#deleteModal -->