<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate("front")) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        // MAIN CSS (REQUIRED ALL PAGE)
        ->appendStylesheet($this->basePath() . '/css/test.css')
    ?>
    <!-- Scripts -->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/test.js', 'text/javascript')
    ?>

</head>
<body>

    <?php echo $this->partial('partial/layout/header'); ?>

    <?php echo $content; ?>

    <?php echo $this->partial('partial/layout/footer'); ?>

    <?php echo $this->inlineScript()
        ->appendFile($this->basePath() . '/js/bootstrap-front.min.js')
    ?>

</body>
</html>
