

<?php if(!isset($contact)): ?>

    <?php if(!empty($bestsellers)): ?>

        <!-- Shop Section -->
        <section class="page-section">
            <div class="container relative">

                <h2 class="font-alt align-center mb-70 mb-sm-40">
                    <?php echo $this->translate('Bestsellery w ofercie') ?>

                    <span class="section-title font-alt align-center mb-70 mb-sm-40"
                          style="position: absolute; right: 3%;">

<!--                    <a href="#" class="section-more right" style="letter-spacing: 0.2em !important;">Zobacz-->
<!--                        wszystkie <i class="fa fa-angle-right"></i></a>-->

                </span>

                </h2>

                <div class="row multi-columns-row">

                    <div class="best owl-carousel">

                        <?php /* @var $best \Product\Model\Product */ ?>
                        <?php foreach($bestsellers as $best): ?>
                            <?php $bestFile = $best->getFilenameMain() ?>

                            <!-- Shop Item -->
                            <div class="col-md-12 col-lg-12 mb-60 mb-xs-40 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                                <div class="post-prev-img">

                                    <?php if(isset($bestFile)): ?>

                                        <a href="<?php echo $this->url('offer', array('lang' => $lang, 'slug' => $best->getSlug(), 'id' => $best->getId())) ?>"><img src="<?php echo $this->url('thumb', array('entity' => 'product', 'size' => '262x336', 'filename' => $bestFile))?>" alt=""/></a>

                                    <?php else: ?>

                                        <a href="<?php echo $this->url('offer', array('lang' => $lang, 'slug' => $best->getSlug(), 'id' => $best->getId())) ?>"><img src="/images/shop/shop-prev-1.jpg" alt=""/></a>

                                    <?php endif ?>

                                </div>
                                <div class="post-prev-title font-alt align-center">
                                    <a href="<?php echo $this->url('offer', array('lang' => $lang, 'slug' => $best->getSlug(), 'id' => $best->getId())) ?>"><?php echo $best->getProductName() ?></a>
                                </div>
                                <div class="post-prev-title font-alt align-center">
                                    <a style="font-size: 12px" href="<?php echo $this->url('offer', array('lang' => $lang, 'slug' => $best->getSlug(), 'id' => $best->getId())) ?>"><?php echo $best->getCategoryName() ?></a>
                                </div>
                                <div class="post-prev-more align-center">
                                    <a href="<?php echo $this->url('offer', array('lang' => $lang, 'slug' => $best->getSlug(), 'id' => $best->getId())) ?>" class="btn btn-mod btn-gray btn-round"><?php echo $this->translate('Zobacz więcej') ?> <i class="fa fa-angle-right"></i></a>
                                </div>
                            </div>
                            <!-- End Shop Item -->

                        <?php endforeach ?>

                    </div>

                </div>

            </div>
        </section>
        <!-- End Shop Section -->

    <?php endif ?>


    <!-- Newsletter Section -->
    <section class="small-section bg-gray-lighter parallax-11" data-background="<?php echo $this->basePath('images/8.jpg') ?>">
        <div class="container relative">

            <form class="form align-center" id="mailchimp">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">

                        <div class="newsletter-label font-alt" style="color: white; opacity: .9">
                            <?php echo $this->translate('Zapisz się do naszego newslettera'); ?>
                        </div>

                        <div class="mb-20">
                            <input placeholder="<?php echo $this->translate('Wpisz adres email'); ?>"
                                   class="newsletter-field form-control input-md round mb-xs-10" type="email"
                                   pattern=".{5,100}" required/>

                            <button id="newsletter-submit" type="submit" class="btn btn-mod btn-medium btn-round mb-xs-10 subs">
                                <?php echo $this->translate('Subskrybuj');?>
                            </button>
                        </div>

                        <div class="newsletter-label font-alt" style="color: white; opacity: .9; font-size: 13px">
                            <?php echo $this->translate('Nigdy nie wysyłamy spamu'); ?>
                        </div>

                        <div id="subscribe-result"></div>

                    </div>
                </div>
            </form>

        </div>
    </section>
    <!-- End Newsletter Section -->



    <!-- Contact Section -->
    <section class="page-section" id="contact">
        <div class="container relative">

            <h2 class="font-alt mb-70 mb-sm-40 text-center">
                <?php echo $this->translate('Kontakt'); ?>
            </h2>

            <p class="text-center" style="font-size: 22px; text-transform: uppercase; letter-spacing: 3px;">
                <span style="font-weight: bold">Tartak bogdan Michalski</span> | racot, ul. szkolna 23 | 64-000 Kościan <br/>
                tel.: 65 513 14 54 | fax.: 65 513 10 11 | <span style="text-transform: lowercase">biuro@tartakmichalski.pl</span>
            </p>

            <p class="text-center" style="font-size: 16px; text-transform: uppercase;">
                Konto bankowe: <br/>
                Bank Spółdzielczy w Kościanie <br/>
                44-8666-0004-0101-0894-2000-0002 <br/>
            </p>

            <p class="text-center" style="font-size: 16px; text-transform: uppercase;">
                Tarcica sucha: kom. 515 659 333 <br>
                Deski podłogowe, tarasowe, schody, drzwi: Maciej Nowak kom. 502 074 950
            </p>

            <!-- Contact Form -->
            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                    <form class="form contact-form" id="contact_form">
                        <div class="clearfix">

                            <div class="cf-left-col">

                                <!-- Name -->
                                <div class="form-group">
                                    <input type="text" name="name" id="name" class="input-md round form-control" placeholder="<?php echo $this->translate('Imię'); ?>" pattern=".{3,100}" required>
                                </div>

                                <!-- Email -->
                                <div class="form-group">
                                    <input type="text" name="surname" id="surname" class="input-md round form-control" placeholder="<?php echo $this->translate('Nazwisko'); ?>" pattern=".{5,100}" required>
                                </div>

                            </div>

                            <div class="cf-right-col">

                                <!-- Message -->
                                <div class="form-group">
                                    <textarea name="message" id="message" class="input-md round form-control" style="height: 84px;" placeholder="<?php echo $this->translate('Wiadomość'); ?>"></textarea>
                                </div>

                            </div>

                        </div>

                        <div class="clearfix">

                            <div class="cf-left-col">

                                <!-- Name -->
                                <div class="form-group">
                                    <input type="text" name="phone" id="phone" class="input-md round form-control" placeholder="<?php echo $this->translate('Telefon'); ?>" pattern=".{3,100}" required>
                                </div>

                            </div>

                            <div class="cf-right-col">

                                <!-- Send Button -->
                                <div class="align-right pt-10">
                                    <button class="submit_btn btn btn-mod btn-medium btn-round" id="submit_btn"><?php echo $this->translate('Wyślij wiadomość'); ?></button>
                                </div>

                            </div>

                        </div>



                        <div id="result"></div>
                    </form>

                </div>
            </div>
            <!-- End Contact Form -->

        </div>
    </section>
    <!-- End Contact Section -->

<?php endif ?>

<!-- Call Action Section -->
<section class="small-section bg-dark">
    <div class="container relative">

        <div class="align-center">
            <h3 class="banner-heading font-alt"><?php echo $this->translate('Dołącz do naszych znajomych'); ?></h3>

            <div>
                <a href="https://www.facebook.com/tartakmichalski" class="btn btn-mod btn-w btn-medium btn-round" style="background: #c9baa9"><img src="<?php echo $this->basePath('images/facebook.png') ?>" alt="facebook"/></a>
            </div>
        </div>

    </div>
</section>
<!-- End Call Action Section -->

<!-- Google Map -->
<div class="google-map">
    <div data-address="Szkolna 23, 64-005 Racot" id="map-canvas"></div>

    <div class="map-section">

        <div class="map-toggle">
            <div class="mt-icon">
                <i class="fa fa-map-marker"></i>
            </div>
            <div class="mt-text font-alt">
                <div class="mt-open"><?php echo $this->translate('Otwórz') ?><i class="fa fa-angle-down"></i></div>
                <div class="mt-close"><?php echo $this->translate('Schowaj') ?> <i class="fa fa-angle-up"></i></div>
            </div>
        </div>

    </div>
</div>
<!-- End Google Map -->

<!-- Call Action Section -->
<section class="small-section bg-dark" style="z-index: 2;">
    <div class="container relative">

        <div class="align-center">
            <img src="<?php echo $this->basePath('images/logo_tartak_1.svg') ?>" alt="logo" class="img-responsive center-block" style="height: 100px"/>
        </div>

    </div>
</section>
<!-- End Call Action Section -->
<!-- Foter -->
<footer class="page-section bg-gray-lighter footer pb-20 pt-20">
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                COPYRIGHT © 2015 TARTAK MICHALSKI.. WSZELKIE PRAWA ZASTRZEŻONE <br/>
                DESIGNED BY <a href="http://dnastudio.pl/">DNA STUDIO</a> <br/>
                <img src="<?php echo $this->basePath('img/unia-na-strone.jpg') ?>" alt=""/>
            </div>
        </div>



    </div>


    <!-- Top Link -->
    <div class="local-scroll">
        <a href="#top" class="link-to-top"><i class="fa fa-caret-up"></i></a>
    </div>
    <!-- End Top Link -->

</footer>
<!-- End Foter -->


</div>
<!-- End Page Wrap -->