<!-- * * * * * * * * * * * * * * * * * *
                CONTACT US SECTION
    * * * * * * * * * * * * * * * * * * * -->
    <section class="az-contact-us-section-wrapper az-section">
        <div class="container">
            <div class="row">
                <!-- SECTION HEADER -->
                <div class="az-section-headers">
                    <h1>KONTAKT Z ZESPOŁEM</h1>

                    <h3>pisz lub dzwoń</h3>
                </div>
                <!-- SECTION HEADER END -->


                <!-- CONTACT DETAILS -->
                <div class="az-contact-details">
                    <div class="az-contact-form-wrapper col-md-8 col-sm-7 col-xs-12">
                        <p>Napisz do nas e-mail poprzez formularz lub wyślij do nas na adres <span
                                class="az-color-bold-text">lombard@lombard.pl</span></p>

                        <form action="#" class="az-contact-form">
                            <div class="az-name-field az-input-wrapper">
                                <label for="az-input-name">Imię*</label>
                                <input type="text" name="az-input-name" id="az-input-name">
                            </div>

                            <div class="az-email-field az-input-wrapper">
                                <label for="az-input-email">Email*</label>
                                <input type="email" name="az-input-email" id="az-input-email">
                            </div>

                            <div class="az-subject-field az-input-wrapper">
                                <label for="az-input-subject">Temat*</label>
                                <input type="text" name="az-input-subject" id="az-input-subject">
                            </div>

                            <div class="az-message-field az-textarea-wrapper">
                                <label for="az-textarea-message">Wiadomość*</label>
                                <textarea name="az-textarea-message" id="az-textarea-message" cols="30"
                                          rows="10"></textarea>
                            </div>

                            <div class="az-submit-field">
                                <input type="submit" id="wyslij" value="WYŚLIJ">
                            </div>
                        </form>
                    </div>

                    <!-- CONTACT ADDRESS -->
                    <div class="az-contact-address-wrapper col-md-4 col-sm-4 col-xs-12">

                        <!-- Grzegorz -->
                        <div class="az-contact-address">
                            <h4>Manager zespołu</h4>
                            <ul>
                                <li>
                                    <i class="pe-7s-user"></i> Grzegoż Stróżniak
                                </li>
                                <li>
                                    <i class="pe-7s-map-marker"></i> ul. Stokrotkowa 47, 60-175 Poznań
                                </li>
                                <li>
                                    <i class="pe-7s-call"></i> +48 601 71 50 71
                                </li>
                                <li>
                                    <i class="pe-7s-mail"></i> grzegorz@lombard.pl
                                </li>
                            </ul>
                        </div>
                        <!-- Grzegorz END -->

                        <!-- Marta -->
                        <div class="az-contact-address">
                            <h4>PR Manager</h4>
                            <ul>
                                <li>
                                    <i class="pe-7s-user"></i> Marta Cugier
                                </li>
                                <li>
                                    <i class="pe-7s-call"></i> +48 693 71 50 71
                                </li>
                                <li>
                                    <i class="pe-7s-mail"></i> marta@lombard.pl
                                </li>
                            </ul>
                        </div>
                        <!-- Marta END -->

                    </div>
                    <!-- CONTACT ADDRESS END -->
                </div>
            </div>
            <!-- CONTACT DETAILS END -->
        </div>
    </section>
    <!-- CONTACT US SECTION END -->

<?php if(!isset($kontakt)): ?>

<!-- * * * * * * * * * * * * * * * * * *
                   FOOTER
    * * * * * * * * * * * * * * * * * * * -->
    <footer class="az-footer">
        <div class="container-fluid">
            <div class="row">
                <!-- ABOUT WIDGET -->
                <div class="az-footer-managament">
                    <h3 class="az-footer-widget-header">Managament</h3>

                    <div class="az-footer-about-us">
                        <p>Jeśli chcesz skontaktować się z nami w celu bookingu koncertu, realicji dźwieku, sceny bądź
                            szukasz firmy zajmującej się TECHNIKĄ ESTRADOWĄ z danego regionu, spełniającą ridery
                            techniczne zespołu Lombard. </p>
                        <a href="<?php echo $this->url('view-page', array('url' => 'kontakt')) ?>" class="az-read-more">zobacz więcej</a>
                    </div>

<!--                    <a href="blog-single.html" class="az-read-more">zobacz więcej</a>-->
                </div>
            </div>
        </div>
    </footer>

<?php else: ?>

<footer class="az-footer">


<div class="container-fluid">
    <div class="row">
        <!-- ABOUT WIDGET -->
        <div class="az-footer-widget">
            <h3 class="az-footer-widget-header">REALIZATOR DŹWIĘKU</h3>

            <div class="az-footer-about-us">
                <p>REJESTRACJA, REALIZACJA I POSTPRTODUKCJA DŹWIĘKU</p>
                <ul>
                    <li>
                        <i class="pe-7s-user"></i> MIREK WDOWCZYK
                    </li>
                    <li>
                        <i class="pe-7s-call"></i> +48 609 71 50 71
                    </li>
                    <li>
                        <i class="pe-7s-mail"></i> mireksound@lombard.pl
                    </li>
                </ul>
            </div>
        </div>
        <!-- ABOUT WIDGET END -->

        <!-- RECENT POST WIDGET -->
        <div class="az-footer-widget">
            <h3 class="az-footer-widget-header">REALIZATOR SCENY</h3>

            <div class="az-footer-about-us">
                <p>REJESTRACJA, REALIZACJA I POSTPRTODUKCJA DŹWIĘKU</p>
                <ul>
                    <li>
                        <i class="pe-7s-user"></i> ŁUKASZ MIGDALISKI
                    </li>
                    <li>
                        <i class="pe-7s-call"></i> +48 601 71 50 71
                    </li>
                    <li>
                        <i class="pe-7s-mail"></i> lukasz@lombard.pl
                    </li>
                </ul>
            </div>
        </div>
        <!-- RECENT POST WIDGET END -->

        <!-- CATEGORY WIDGET -->
        <div class="az-footer-widget">
            <h3 class="az-footer-widget-header">REALIZATOR ŚWIATEŁ</h3>

            <div class="az-footer-about-us">
                <p>ŚWIATŁA</p>
                <ul>
                    <li>
                        <i class="pe-7s-user"></i> ŁUKASZ JARMUZIEWICZ
                    </li>
                    <li>
                        <i class="pe-7s-call"></i> +48 530 600 604
                    </li>
                    <li>
                        <i class="pe-7s-mail"></i> looklight@lombard.pl
                    </li>
                </ul>
            </div>
        </div>
        <!-- CATEGORY WIDGET END -->


        <!-- PHOTO GALLERY WIDGET -->
        <div class="az-footer-widget">
            <h3 class="az-footer-widget-header">OPRAWA MULTIMEDIALNA</h3>

            <div class="az-footer-about-us">
                <p>ZESPÓŁ LOMBARD POSIADA WŁASNE 3 PROJEKTORY SANYO 12 000 ANSI I 3 EKRANY 3X4M, ISTNIEJE MOŻLIWOŚĆ POSZERZENIA OFERTY O EKRANY DIODOWE I TELEWIZORY 52''</p>
                <ul>
                    <li>
                        <i class="pe-7s-user"></i> GRZEGORZ STRÓŻNIAK
                    </li>
                    <li>
                        <i class="pe-7s-call"></i> +48 601 71 50 71
                    </li>
                    <li>
                        <i class="pe-7s-mail"></i> grzegorz@lombard.pl
                    </li>
                </ul>
            </div>
        </div>
        <!-- FOOTER END -->
    </div>
    </div>
    </footer>
<?php endif ?>


</div>

<!-- ABOUT WIDGET END -->


<!-- FIXED SOCIAL ICON & COPYRIGHT TEXT -->

<!-- SOCIAL ICON -->
<div class="az-fixed-social-icon">
    <ul>
        <li>
            <a href="#"><i class="allegro"></i></a>
        </li>
        <li>
            <a href="https://pl-pl.facebook.com/zespol.lombard/"><i class="fa fa-facebook"></i></a>
        </li>
        <li>
            <a href="#"><i class="fa fa-instagram"></i></a>
        </li>
        <li>
            <a href="#"><i class="fa fa-google-plus"></i></a>
        </li>
        <li>
            <a href="https://www.youtube.com/user/lombardTV"><i class="fa fa-youtube"></i></a>
        </li>
        <li>
            <a href="https://play.spotify.com"><i class="fa fa-spotify"></i></a>
        </li>
    </ul>
</div>
<!-- SOCIAL ICON END -->

<!-- COPYRIGHT TEXT -->
<div class="az-copyright-text">
    <p>&copy; COPYRIGHT <a href="#" class="az-company-name">LOMBARD</a> 2015. Designed by <a
            class="az-company-name">DNA Studio.</a></p>
</div>
<!-- COPYRIGHT TEXT END -->
<!-- FIXED SOCIAL ICON & COPYRIGHT TEXT END -->