<!-- Newsletter Section -->
<section class="small-section bg-gray-lighter">
    <div class="container relative">

        <form class="form align-center" id="mailchimp">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                    <div class="newsletter-label font-alt">
                        Newsletter
                    </div>

                    <div class="mb-20">
                        <input placeholder="Wpisz swoj email" class="newsletter-field form-control input-md round mb-xs-10" type="email" pattern=".{5,100}" required/>

                        <button id="newsletter-submit" type="submit" class="btn btn-mod btn-medium btn-round mb-xs-10">
                            Subskrybuj
                        </button>
                    </div>

                    <div class="form-tip">
                        <i class="fa fa-info-circle"></i> Zaufaj nam, nigdy nie wysyłamy spamu
                    </div>

                    <div id="subscribe-result"></div>

                </div>
            </div>
        </form>

    </div>
</section>
<!-- End Newsletter Section -->


<!-- Contact Section -->
<section class="page-section" id="contact">
    <div class="container relative">

        <h2 class="section-title font-alt mb-70 mb-sm-40">
            Znajdź nas
        </h2>

        <div class="row">

            <div class="col-md-8 col-md-offset-2">
                <div class="row">

                    <!-- Phone -->
                    <div class="col-sm-6 col-lg-4 pt-20 pb-20 pb-xs-0">
                        <div class="contact-item">
                            <div class="ci-icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="ci-title font-alt">
                                Call Us
                            </div>
                            <div class="ci-text">
                                +48 664 374 639
                            </div>
                        </div>
                    </div>
                    <!-- End Phone -->

                    <!-- Address -->
                    <div class="col-sm-6 col-lg-4 pt-20 pb-20 pb-xs-0">
                        <div class="contact-item">
                            <div class="ci-icon">
                                <i class="fa fa-map-marker"></i>
                            </div>
                            <div class="ci-title font-alt">
                                Address
                            </div>
                            <div class="ci-text">
                                Warszawa
                            </div>
                        </div>
                    </div>
                    <!-- End Address -->

                    <!-- Email -->
                    <div class="col-sm-6 col-lg-4 pt-20 pb-20 pb-xs-0">
                        <div class="contact-item">
                            <div class="ci-icon">
                                <i class="fa fa-envelope"></i>
                            </div>
                            <div class="ci-title font-alt">
                                Email
                            </div>
                            <div class="ci-text">
                                <a href="mailto:biuro@web-ir.pl">biuro@web-ir.pl</a>
                            </div>
                        </div>
                    </div>
                    <!-- End Email -->

                </div>
            </div>

        </div>

    </div>
</section>
<!-- End Contact Section -->

<!-- Call Action Section -->
<section class="small-section bg-dark">
    <div class="container relative">

        <div class="align-center">
            <h3 class="banner-heading font-alt">Want to discuss your new project?</h3>
            <div>
                <a href="" class="btn btn-mod btn-w btn-medium btn-round">Lets tallk</a>
            </div>
        </div>

    </div>
</section>
<!-- End Call Action Section -->


<!-- Foter -->
<footer class="page-section bg-gray-lighter footer pb-60">
    <div class="container">

        <!-- Footer Logo -->
        <div class="local-scroll mb-30 wow fadeInUp" data-wow-duration="1.5s">
            <a href="#top"><img src="img/logo.png" width="78" height="36" alt="" /></a>
        </div>
        <!-- End Footer Logo -->

        <!-- Social Links -->
<!--        <div class="footer-social-links mb-110 mb-xs-60">-->
<!--            <a href="#" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>-->
<!--            <a href="#" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>-->
<!--            <a href="#" title="Behance" target="_blank"><i class="fa fa-behance"></i></a>-->
<!--            <a href="#" title="LinkedIn+" target="_blank"><i class="fa fa-linkedin"></i></a>-->
<!--            <a href="#" title="Pinterest" target="_blank"><i class="fa fa-pinterest"></i></a>-->
<!--        </div>-->
        <!-- End Social Links -->

        <!-- Footer Text -->
        <div class="footer-text">

            <!-- Copyright -->
            <div class="footer-copy font-alt">
                <a href="http://web-ir.pl" target="_blank">&copy; web-ir 2015</a>.
            </div>
            <!-- End Copyright -->

<!--            <div class="footer-made">-->
<!--                Made with love for great people.-->
<!--            </div>-->

        </div>
        <!-- End Footer Text -->

    </div>


    <!-- Top Link -->
    <div class="local-scroll">
        <a href="#top" class="link-to-top"><i class="fa fa-caret-up"></i></a>
    </div>
    <!-- End Top Link -->

</footer>
<!-- End Foter -->