<?php
    $ulClass = 'clearlist';
    $liClass = '';
    $subUlClass = '';
    $subLiClass = '';
?>

<!-- Page Loader -->
<div class="page-loader">
    <div class="loader">Loading...</div>
</div>
<!-- End Page Loader -->

<!-- Page Wrap -->
<div class="page" id="top">

    <?php if(isset($home) && $home == 'home'): ?>

        <?php if(!empty($items)): ?>

            <!-- Fullwidth Slider -->
            <div class="home-section fullwidth-slider bg-dark" id="home">

                <?php /* @var $item \CmsIr\Slider\Model\SliderItem */ ?>
                <?php foreach($items as $item): ?>

                <!-- Slide Item -->
                    <section class="home-section bg-scroll bg-dark-alfa-30" data-background="<?php echo $this->basePath('files/slider/' . $item->getFilename()) ?>">
                        <div class="js-height-full container">

                            <!-- Hero Content -->
                            <div class="home-content">
                                <div class="home-text">

                                    <img src="<?php echo $this->basePath('images/mystery.png') ?>" alt="mystery"/>

                                    <div class="local-scroll" style="margin-bottom: -150px; margin-top: 150px">
                                        <img src="<?php echo $this->basePath('images/logo.png') ?>" alt="logo" class="img-responsive center-block"/>
                                    </div>


                                    <h3 class="poznaj-nas">POZNAJ NAS</h3>


                                </div>
                            </div>
                            <!-- End Hero Content -->

                            <div class="local-scroll">
                                <a href="#historia" class="scroll-down"><i class="fa fa-angle-down scroll-down-icon"></i></a>
                            </div>

                        </div>
                    </section>
                    <!-- End Slide Item -->

                <?php endforeach ?>

            </div>
            <!-- End Fullwidth Slider -->

        <?php endif ?>

    <?php endif ?>

    <!-- Navigation panel -->
    <nav class="main-nav dark transparent stick-fixed">
        <div class="full-wrapper relative clearfix">
            <!-- Logo ( * your text or image into link tag *) -->
            <div class="nav-logo-wrap local-scroll">
                <a href="<?php echo $this->url('home') ?>" class="logo">
                    <img src="<?php echo $this->basePath('images/tartak_logo_2.svg') ?>" alt="logo" class="logo-menu" style="width: 450px;"/>
                </a>
            </div>
            <div class="mobile-nav">
                <i class="fa fa-bars"></i>
            </div>

            <!-- Main Menu -->
            <div class="inner-nav desktop-nav">

                <?php echo $this->menuHelper()->renderMenu($menu, $ulClass, $liClass, $subUlClass, $subLiClass, null, $langId, $lang); ?>

                <li>
                    <a href="#" class="mn-has-sub"><i class="fa fa-angle-down"></i> <?php echo $langUp ?></a>

                    <ul class="mn-sub">

                        <?php
                            switch ($langUp) {
                                case 'PL':
                                    echo '<li><a href="' . $this->url('home', array('lang' => 'en')) . '">Angielski</a></li>';
                                    echo '<li><a href="' . $this->url('home', array('lang' => 'de')) . '">Niemiecki</a></li>';
                                    break;
                                case 'EN':
                                    echo '<li><a href="' . $this->url('home', array('lang' => 'pl')) . '">Polski</a></li>';
                                    echo '<li><a href="' . $this->url('home', array('lang' => 'de')) . '">Niemiecki</a></li>';
                                    break;
                                case 'DE':
                                    echo '<li><a href="' . $this->url('home', array('lang' => 'pl')) . '">Polski</a></li>';
                                    echo '<li><a href="' . $this->url('home', array('lang' => 'en')) . '">Angielski</a></li>';
                                    break;
                            }
                        ?>

                    </ul>

                </li>

                </ul>

            </div>
            <!-- End Main Menu -->


        </div>
    </nav>
    <!-- End Navigation panel -->
