<?php
    $ulClass = 'nav navbar-nav';
    $liClass = '';
    $subUlClass = '';
    $subLiClass = '';
?>
<div class="az-main-page-contents">

    <header class="az-fixed-header">
        <div class="container-fluid">
            <div class="row">
                <!-- Navigation Menu start-->
                <nav class="navbar az-main-menu" role="navigation">
                    <!-- Navbar Toggle -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <!-- Logo góra strony-->
                        <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img class="logo" id="logo"
                                   src="/images-front/logo-lombard.svg" width="120px"
                                   alt="Lombard"></a>

                    </div>
                    <!-- Navbar Toggle End -->

                    <!-- navbar-collapse start-->
                    <div id="nav-menu" class="navbar-collapse collapse" role="navigation">
                        <?php echo $this->menuHelper()->renderMenu($menu, $ulClass, $liClass, $subUlClass, $subLiClass); ?>
                    </div>
                    <!-- navbar-collapse end-->
                </nav>
                <!-- Navigation Menu end-->
            </div>
        </div>
    </header>
