<?php
    $ulClass = 'clearlist';
    $liClass = '';
    $subUlClass = '';
    $subLiClass = '';
?>

<!-- Page Loader -->
<div class="page-loader">
    <div class="loader">Loading...</div>
</div>
<!-- End Page Loader -->

<!-- Page Wrap -->
<div class="page" id="top">

<?php if(!empty($items)): ?>

    <!-- Fullwidth Slider -->
    <div class="home-section fullwidth-slider bg-dark" id="home">

        <?php /* @var $item \CmsIr\Slider\Model\SliderItem */ ?>
        <?php foreach($items as $item): ?>

            <!-- Slide Item -->
            <section class="home-section bg-scroll bg-dark-alfa-30" data-background="<?php echo $this->basePath('files/slider/' . $item->getFilename()) ?>">
                <div class="js-height-full container">

                    <!-- Hero Content -->
                    <div class="home-content">
                        <div class="home-text">

                            <h2 class="hs-line-14 font-alt mb-50 mb-xs-30">
                                <?php echo $item->getTitle() ?>
                            </h2>

                            <h1 class="hs-line-8 no-transp font-alt mb-50 mb-xs-30">
                                <?php echo $item->getSubtitle()?>
                            </h1>

                        </div>
                    </div>
                    <!-- End Hero Content -->

                </div>
            </section>
            <!-- End Slide Item -->

        <?php endforeach ?>

    </div>
    <!-- End Fullwidth Slider -->

<?php endif ?>

<!-- Navigation panel -->
<nav class="main-nav dark transparent stick-fixed">
    <div class="full-wrapper relative clearfix">
        <!-- Logo ( * your text or image into link tag *) -->
        <div class="nav-logo-wrap local-scroll">
            <a href="<?php echo $this->url('home') ?>" class="logo">
                <img src="<?php echo $this->basePath('img/logo-login.png') ?>" alt="logo" class="logo-menu" />
            </a>
        </div>
        <div class="mobile-nav">
            <i class="fa fa-bars"></i>
        </div>

        <!-- Main Menu -->
        <div class="inner-nav desktop-nav">

            <?php echo $this->menuHelper()->renderMenu($menu, $ulClass, $liClass, $subUlClass, $subLiClass, null, $langId, $lang); ?>

            <li>
                <a href="#" class="mn-has-sub"><i class="fa fa-angle-down"></i> <?php echo $langUp ?></a>

                <ul class="mn-sub">

                    <?php
                    switch ($langUp) {
                        case 'PL':
                            echo '<li><a href="' . $this->url('home', array('lang' => 'en')) . '">Angielski</a></li>';
                            echo '<li><a href="' . $this->url('home', array('lang' => 'de')) . '">Niemiecki</a></li>';
                            break;
                        case 'EN':
                            echo '<li><a href="' . $this->url('home', array('lang' => 'pl')) . '">Polish</a></li>';
                            echo '<li><a href="' . $this->url('home', array('lang' => 'de')) . '">German</a></li>';
                            break;
                        case 'DE':
                            echo '<li><a href="' . $this->url('home', array('lang' => 'pl')) . '">Polnisch</a></li>';
                            echo '<li><a href="' . $this->url('home', array('lang' => 'en')) . '">Englisch</a></li>';
                            break;
                    }
                    ?>

                </ul>

            </li>

            </ul>

        </div>
        <!-- End Main Menu -->


    </div>
</nav>
<!-- End Navigation panel -->
